### ISSUE TITLE
Test if sassyjson works with libsass v2.0

### ISSUE THREAD

**Issue by FWeinb** [HugoGiraudel/SassyJSON#76]
Just curious if this will work.  [Release Notes](https://github.com/hcatlin/libsass/releases/tag/v2.0)

**Comment by jpdesigndev** [comment]
Are there any plans on supporting libsass?

What about libsass 3.1? It could work out of the box.

**Comment by HugoGiraudel** [comment]
SassyJSON is an experiment and should not be used in a real live project. Hence, there is no plan on supporting LibSass.
