### ISSUE TITLE
Problem with "n" and "r"

### ISSUE THREAD

**Issue by thierrymichel** [HugoGiraudel/SassyJSON#85]
Hi Hugo,

I hope you're okay since the last time.

I try to share my breakpoints between Sass and JS.
So I came to your SassyJSON! Thanks for the great job!

I just have some problems when I use a "r" or a "n" inside a 'key string', like this :

```
@import "SassyJSON";
$foo: json-decode('{"narrow": "768px"}');
.bar {
  output: map-keys($foo); // "\a     a\a     \a     ow"
}
```

Any idea?
Thierry

**Comment by HugoGiraudel** [comment]
I think it's because of escaped characters. SassyJSON should not be used in any serious project, it's broken and not really fixable anymore. I'd recommend using something like https://github.com/acdlite/json-sass or equivalent.

**Comment by thierrymichel** [comment]
Thanks, I have jumped to json-sass and updated my gulp workflow…
Works fine :)
