### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by carljm** [HugoGiraudel/SassyJSON#91]
Any planned schedule for an npm release? The recently-fixed quoting bug is a deal-breaker for use with libsass.

Thanks! (We're using this project in our recent work on living styleguides...)

**Comment by HugoGiraudel** [comment]
Nope. SassyJSON should not be used.

**Comment by carljm** [comment]
Ha! Care to elaborate on that?

We're actually finding it quite useful for living styleguides - exporting a config map (e.g. colors) from Sass to JSON allows the styleguide to e.g. iterate over the colors in a template and show a swatch for each, which isn't possible otherwise. Do you have a preferable solution in mind for that?

If you don't have a better solution in mind, and your belief is that SassyJSON should not be used and thus you don't plan to maintain it, how would you feel about transferring maintainership?

**Comment by HugoGiraudel** [comment]
SassyJSON was an experiment. It is not meant to be used in production and has never meant to be used in production. Is it a JSON parser written in Sass, by a wannabe developer. This is a recipe for disaster.

I recommend you use a clean Sass plugin, either through Ruby, or through Eyeglass or Sassport.

**Comment by carljm** [comment]
Hmm. We're using only the JSON export, not import, which seems (relatively) more straightforward. No disasters experienced thus far, and styleguide generation is only marginally "production" :-)

I don't think Eyeglass is helpful in this case (unless I'm missing something it does). It does seem like sassport might provide a workable alternative, though; I'll look into that.

**Comment by HugoGiraudel** [comment]
I would recommend extracting the export part (which is quite straightforward and easy to maintain indeed) for your own purposes.

**Comment by carljm** [comment]
Thanks for the clarity, and recommendations!

**Comment by carljm** [comment]
Just FYI, we have extracted just the export part here: https://github.com/oddbird/sass-json-export (not yet released on npm).
